#pragma once

#include "MarioSmall.h"
#include "MarioBig.h"
#include "Goomba.h"
#include "ParaGoomba.h"
#include "Koopa.h"
#include "ParaKoopa.h"
#include "QuestionBlock.h"
#include "Brick.h"
#include "CollisionWallType1.h"
#include "CollisionWallType2.h"
#include "Coin.h"
#include "Mushroom.h"
#include "CoinUp.h"
#include "GoalRoulette.h"

#include "WMNode.h"
#include "WMBush.h"
#include "WMMario.h"
#include "WMHelpBubble.h"
