#pragma once
//Notes: this header do not includes all entities but only the ones that are needed when loading a scene

#include "MarioSmall.h"
#include "MarioSuper.h"
#include "Goomba.h"
#include "ParaGoombaRed.h"
#include "ParaGoombaBrown.h"
#include "Koopa.h"
#include "ParaKoopa.h"
#include "VenusFireTrap.h"
#include "PiranhaPlant.h"
#include "BoomerangBrother.h"
#include "QuestionBlock.h"
#include "Brick.h"
#include "ItemWoodBlock.h"
#include "NoteBlock.h"
#include "SuperNoteBlock.h"
#include "CollisionWallType1.h"
#include "CollisionWallType2.h"
#include "Coin.h"
#include "Mushroom.h"
#include "CoinUp.h"
#include "GoalRoulette.h"

#include "WMNode.h"
#include "WMBush.h"
#include "WMMario.h"
#include "WMHelpBubble.h"
