#pragma once

enum class PointType {
	ONE_HUNDRED_POINTS,
	TWO_HUNDRED_POINTS,
	FOUR_HUNDRED_POINTS,
	EIGHT_HUNDRED_POINTS,
	ONE_THOUSAND_POINTS,
	TWO_THOUSAND_POINTS,
	FOUR_THOUSAND_POINTS,
	EIGHT_THOUSAND_POINTS,
	ONE_UP,
};